# Staying on version 2.x for performance tuning cpu, memory resources.
# Ver. 3.x is meant for swarms and is not 100% backwards-compat.
version: '2.4'
networks:
  default:
    external: true
    name: localenv

services:

  # Drupal image provides app volume, which contains the application code.
  drupal:
    image: alexanderallen/drupal-8.prod:alpine-3.11
    volumes:
      - app:/app

  nginx:
    image: alexanderallen/nginx:1.17-alpine
    tty: true
    ports:
      - 80:8080
      - 443:443
    healthcheck:
      test: curl --fail -s http://localhost:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
    volumes:
      - app:/app

  mysql:
    hostname: mysql
    image: alexanderallen/mariadb-alpine:10.4.10-r0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  memcached:
    # Memcached 1.5.20 released Nov 11, 2019.
    # https://hub.docker.com/_/memcached
    image: memcached:1.5.20-alpine
    command: -p 11211 -m 16 -vvv -M

  php-fpm:
    # Prod image.
    image: alexanderallen/php7-fpm.core:alpine-3.11
    environment:
      PHP_INI_MAX_EXECUTION_TIME: 0 # Set to 0 for unlimited.
      PHP_INI_MEM_LIMIT: 256M # The default memory limit is 128M.
      # PHP_FPM_LISTEN: 127.0.0.1:9010 # The default port is 9000, which conflicts with XDebug. Move to 9010.
      PHP_FPM_LISTEN: 9010 # The default port is 9000, which conflicts with XDebug. Move to 9010.
      PHP_FPM_WORKER_LOGOUTPUT: 1
    volumes:
      - app:/app
    # todo: healthcheck

volumes:
  mysql:
  app:
