version: '3.5'
networks:
  default:
    external: true
    name: localenv

services:

  nginx:
    image: alexanderallen/nginx:1.17-alpine
    environment:
      PHP_INI_MAX_EXECUTION_TIME: 120 # The defualt is 30, increasing to 60.
      PHP_INI_MEM_LIMIT: 256M # The dfeulat memory limit is 128M.
      PHP_FPM_LISTEN: 127.0.0.1:9010 # The default port is 9000, which conflicts with XDebug. Move to 9010.
    ports:
      - 127.0.0.1:80:8080
      - 127.0.0.1:443:443
    volumes:
      - ./app:/app
    # todo: helthcheck

  mysql:
    hostname: mysql
    image: alexanderallen/mariadb-alpine:10.4.10-r0
    # Map the Docker hosts' 3306 port to container's 3306 for SQL GUI/console access.
    ports:
      - 3306:3306

  memcached:
    # Memcached 1.5.20 released Nov 11, 2019.
    # https://hub.docker.com/_/memcached
    image: memcached:1.5.20-alpine
    command: -p 11211 -m 16 -vvv -M

  php-fpm:
    image: alexanderallen/php-fpm.dev:latest
    environment:
      PHP_INI_MAX_EXECUTION_TIME: 0 # Set to 0 for unlimited.
      PHP_INI_MEM_LIMIT: 256M # The default memory limit is 128M.
      # PHP_FPM_LISTEN: 127.0.0.1:9010 # The default port is 9000, which conflicts with XDebug. Move to 9010.
      PHP_FPM_LISTEN: 9010 # The default port is 9000, which conflicts with XDebug. Move to 9010.
      PHP_FPM_WORKER_LOGOUTPUT: 1
      XDEBUG_REMOTE_PORT: 9000
      XDEBUG_IDE_KEY: 'PHPSTORM'
      XDEBUG_CONNECT_BACK: 0 # Must be disabled in order for remote_host to work.
      XDEBUG_REMOTE_HOST: 10.254.254.254 # Docker for Mac host alias: use it instead of the default gateway 172.18.0.1.
    volumes:
      - ./app:/app
    # todo: healthcheck
