# Staying on version 2.x for performance tuning cpu, memory resources.
# Ver. 3.x is meant for swarms and is not 100% backwards-compat.
# Secrets are available only on 3.x.
version: '3.7'
networks:
  default:
    external: true
    name: ${COMPOSE_NETWORK:-localenv}

services:

  mysql:
    hostname: mysql
    image: alexanderallen/mariadb-alpine:10.4.10-r0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_USER: docker
      PMA_PASSWORD:
      PMA_HOST: mysql

  memcached:
    # Memcached 1.5.20 released Nov 11, 2019.
    # https://hub.docker.com/_/memcached
    image: memcached:1.5.20-alpine
    command: -p 11211 -m 16 -vvv -M

  phpmemcachedadmin:
    image: moonbuggy2000/phpmemcachedadmin:latest
    ports:
      - 8585:8080
    depends_on:
      - memcached
    volumes:
      - ./run/phpmemcachedadmin/Config/Memcache.php:/var/www/html/Config/Memcache.php

volumes:
  mysql:
