version: '3.7'

networks:
  default:
    external: true
    name: localenv

# You need to be on 3.x or greater to use secrets.
# They're not available on 2.x.
secrets:
  ssh_private:
    file: /c/Users/richa/.ssh/id_rsa
  ssh_public:
    file: /c/Users/richa/.ssh/id_rsa.pub

services:

  drush:
    # Without xdebug.
    # image: alexanderallen/php7-cli.drush9:alpine-3.11
    # With xdebug and tools.
    image: alexanderallen/php7-cli-drush9.dev:alpine-3.11
    secrets:
      - ssh_private
      - ssh_public
    environment:
      XDEBUG_SHOW_EXCEPTION_TRACE: 0

    # The Drush Dev container should not make assumptions regarding working_dir, as it can
    # be used to work on any number of projects simulataneously.
    working_dir: /

    volumes:

      # WSL2 to DD bind, performant.
      # $USER variable assumes compose run within WSL and not WIN10.
      # - type: bind
      #   # Bind from WSL.user to continer.
      #   source: "/home/${USER}/Workloads"
      #   # Nobody doesn't have a home in alpine.
      #   target: /home/nobody/Workloads
      #   consistency: consistent

      - "${PROJECT_ROOT}:/app"

    # WSL mounts files as current WSL user, even if user is specified here.
    # This just specifies container user, not mounts user.
    user: nobody


    tty: true
