# Staying on version 2.x for performance tuning cpu, memory resources.
# Ver. 3.x is meant for swarms and is not 100% backwards-compat.
# Secrets are available only on 3.x.
version: '3.7'
networks:
  default:
    external: true
    name: ${COMPOSE_NETWORK:-localenv}

services:

  nginx:
    image: alexanderallen/nginx:1.17-alpine
    tty: true
    ports:
      - 80:8080
      - 443:443
    volumes:
      - drawer:/sock

  mysql:
    hostname: mysql
    image: alexanderallen/mariadb-alpine:10.4.10-r0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_USER: docker
      PMA_PASSWORD:
      PMA_HOST: mysql

  memcached:
    # Memcached 1.5.20 released Nov 11, 2019.
    # https://hub.docker.com/_/memcached
    image: memcached:1.5.20-alpine
    command: -p 11211 -m 16 -vvv -M

  php-fpm:
    # By default use prod image.
    image: "alexanderallen/php7-fpm.${ENVIRONMENT:-prod}:alpine-3.11"
    # Allow nobody user logging to /dev/stdout.
    tty: true
    environment:
      # Currently ignored, hardcoded in
      # build\php-fpm\php-fpm.d\docker-pool.conf
      PHP_FPM_LISTEN: /sock/docker.sock

      PHP_INI_MAX_EXECUTION_TIME: 0 # Set to 0 for unlimited.
      PHP_INI_MEM_LIMIT: 256M # The default memory limit is 128M.
      # PHP_FPM_LISTEN: 127.0.0.1:9010 # The default port is 9000, which conflicts with XDebug. Move to 9010.
      PHP_FPM_WORKER_LOGOUTPUT: 1

    volumes:
      - drawer:/sock

volumes:
  mysql:
  drawer:
